Repository wml-frc/WML, pull requests merged in 2020-01, with the labels that each got.

#16 Added Documentation
  .vscode/settings.json
  README.md
  src/example/Basic Pneumatics/Robot.cpp
  src/example/Basic Pneumatics/Robot.h
  src/example/Gyro Turn/Robot.cpp
  src/example/Gyro Turn/Robot.h
Labels: documentation

#17 Readme Modifications
  README.md
Labels: documentation

#18 Examples
  README.md
  examples/Basic Pneumatics/main/cpp/Robot.cpp
  examples/Basic Pneumatics/main/include/Robot.h
  examples/Gyro Turn/main/cpp/Robot.cpp
  examples/Gyro Turn/main/include/Robot.h
Labels: documentation, enhancement

#22 2020.2.2 update
  build.gradle
  src/main/cpp/MotionProfiling.cpp
  src/main/cpp/RobotStartup.cpp
  src/main/cpp/WMLCtre.robot.cpp
  src/main/cpp/control/Filter.cpp
  src/main/cpp/sensors/NavX.robot.cpp
  src/main/cpp/strategy/MPStrategy.cpp
  src/main/include/MotionProfiling.h
  src/main/include/control/Filter.h
  src/main/include/strategy/MPStrategy.h
  src/simulation/cpp/loader.cpp
  src/simulation/cpp/physics_updater.cpp
  src/simulation/cpp/sensors/NavX.cpp
  src/simulation/cpp/simulation.cpp
  src/simulation/cpp/simulation_startup.cpp
  src/simulation/cpp/ui/window.cpp
  src/simulation/cpp/ui/window_manager.cpp
  src/simulation/cpp/windows/control.cpp
  src/simulation/cpp/windows/drivetrains.cpp
  src/simulation/cpp/windows/elevators.cpp
  src/simulation/cpp/windows/motors.cpp
  src/simulation/cpp/wml_ctre.cpp
  src/simulation/include/simulation/components/encodersim.h
  src/simulation/include/simulation/components/gyrosim.h
  src/simulation/include/simulation/ctre_sim.h
  src/simulation/include/simulation/loader.h
  src/simulation/include/simulation/physics_updater.h
  src/simulation/include/simulation/sensors/navx_sim.h
  src/simulation/include/simulation/simulation.h
  src/simulation/include/simulation/ui/elements.h
  src/simulation/include/simulation/ui/utils.h
  src/simulation/include/simulation/ui/window.h
  src/simulation/include/simulation/windows/control.h
  src/simulation/include/simulation/windows/drivetrains.h
  src/simulation/include/simulation/windows/elevators.h
  src/simulation/include/simulation/windows/motors.h
  src/simulation/resources/2019-field.jpg
  vendordeps/PathfinderOLD.json
  vendordeps/Phoenix.json
  vendordeps/navx_frc.json
Labels: bug, enhancement, urgent
